In [1]:
from csd.utils.util import generate_all_codewords_from_codeword, generate_measurement_matrices

In [2]:
number_modes = 2
cutoff_dim = 3

In [3]:
measurement_matrices = generate_measurement_matrices(num_modes=number_modes, cutoff_dim=cutoff_dim)

In [8]:
measurement_matrices

[array([[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([[0., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([[0., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]], dtype=float32),
 array([[0., 0., 0.],
        [0., 1., 1.],
        [0., 1., 1.]], dtype=float32)]

In [4]:
import numpy as np

In [5]:
alpha_init = 0.1
alpha_end = 1.4
number_points_to_plot = 16
alpha_step = (alpha_end - alpha_init) / number_points_to_plot
alphas = list(np.arange(alpha_init, alpha_end, alpha_step))

In [7]:
alphas[7]

0.6687499999999998

In [1]:
from csd.utils.util import save_object_to_disk, load_object_from_file
from csd.utils.probability import compute_maximum_likelihood
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

In [2]:
batch_success_prob = load_object_from_file('batch_success_prob')
output_batch = load_object_from_file('output_batch')
guessed_codewords_probabilities = compute_maximum_likelihood(batch_success_probabilities=batch_success_prob,
                                                             output_batch=output_batch)
input_batch = load_object_from_file('input_batch')

In [12]:
[output_codeword_prob.binary_code for output_codeword_prob in batch_success_prob[0]]

[{'input_codeword': [0, 0, 0],
  'guessed_codeword': [1, 1, 1],
  'output_codeword': [0, 0, 0],
  'psucc': 0.009605835191905499},
 {'input_codeword': [0, 0, 0],
  'guessed_codeword': [1, 0, 0],
  'output_codeword': [0, 0, 1],
  'psucc': 0.08120762556791306},
 {'input_codeword': [0, 0, 0],
  'guessed_codeword': [1, 1, 1],
  'output_codeword': [0, 1, 0],
  'psucc': 0.001613063970580697},
 {'input_codeword': [0, 0, 0],
  'guessed_codeword': [1, 1, 0],
  'output_codeword': [0, 1, 1],
  'psucc': 0.01363682746887207},
 {'input_codeword': [0, 0, 0],
  'guessed_codeword': [0, 1, 1],
  'output_codeword': [1, 0, 0],
  'psucc': 0.08096113055944443},
 {'input_codeword': [0, 0, 0],
  'guessed_codeword': [1, 0, 1],
  'output_codeword': [1, 0, 1],
  'psucc': 0.6844444870948792},
 {'input_codeword': [0, 0, 0],
  'guessed_codeword': [0, 1, 1],
  'output_codeword': [1, 1, 0],
  'psucc': 0.013595436699688435},
 {'input_codeword': [0, 0, 0],
  'guessed_codeword': [0, 1, 0],
  'output_codeword': [1, 1, 1],

In [10]:
[guessed_codeword_prob.binary_code for guessed_codeword_prob in guessed_codewords_probabilities]

[{'input_codeword': [1, 1, 0],
  'guessed_codeword': [0, 0, 0],
  'output_codeword': [0, 0, 0],
  'psucc': 0.8079701662063599},
 {'input_codeword': [1, 0, 0],
  'guessed_codeword': [0, 0, 1],
  'output_codeword': [0, 0, 1],
  'psucc': 0.7439103722572327},
 {'input_codeword': [1, 1, 0],
  'guessed_codeword': [0, 1, 0],
  'output_codeword': [0, 1, 0],
  'psucc': 0.1415867656469345},
 {'input_codeword': [1, 0, 0],
  'guessed_codeword': [0, 1, 1],
  'output_codeword': [0, 1, 1],
  'psucc': 0.1273678094148636},
 {'input_codeword': [0, 1, 0],
  'guessed_codeword': [1, 0, 0],
  'output_codeword': [1, 0, 0],
  'psucc': 0.7434099912643433},
 {'input_codeword': [0, 0, 0],
  'guessed_codeword': [1, 0, 1],
  'output_codeword': [1, 0, 1],
  'psucc': 0.6844444870948792},
 {'input_codeword': [0, 1, 0],
  'guessed_codeword': [1, 1, 0],
  'output_codeword': [1, 1, 0],
  'psucc': 0.12779557704925537},
 {'input_codeword': [0, 0, 0],
  'guessed_codeword': [1, 1, 1],
  'output_codeword': [1, 1, 1],
  'psuc

In [9]:
one_prob.binary_code

{'input_codeword': [1, 1, 0],
 'guessed_codeword': [0, 0, 0],
 'output_codeword': [0, 0, 0],
 'psucc': 0.8079701662063599}

In [5]:
[codeword.binary_code for codeword in input_batch.codewords]

[[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 0]]

In [6]:
[codeword.binary_code for codeword in output_batch.codewords]

[[0, 0, 0],
 [0, 0, 1],
 [0, 1, 0],
 [0, 1, 1],
 [1, 0, 0],
 [1, 0, 1],
 [1, 1, 0],
 [1, 1, 1]]

In [13]:
success_probability_from_guesses = [codeword_success_prob.success_probability for codeword_success_prob in guessed_codewords_probabilities]
avg_succ_prob =  sum(success_probability_from_guesses) / input_batch.size

In [15]:
avg_succ_prob.numpy()

0.87285525

In [16]:
input_batch.alpha

0.6687499999999998