In [15]:
import numpy as np
import strawberryfields as sf
from strawberryfields.ops import *
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ["TF_FORCE_GPU_ALLOW_GROWTH"] = "true"

In [35]:
from csd.utils.util import create_optimized_parameters_to_print

In [36]:
modes=2
optimized_parameters = [-0.008990095928311348,
                             -1.7685526609420776,
                             -0.00886836089193821,
                            -0.008727652952075005,
                           0.6994574666023254,
                             0.7021579742431641]
circuit_parameters = [alpha_0, alpha_1, theta_1_0, phi_1_0, varphi_1_0, varphi_1_1, a_0, a_1]

In [ ]:
{'theta_1_0': -0.008990095928311348, 
 'phi_1_0': -1.7685526609420776, 
 'varphi_1_0': -0.00886836089193821, 
 'varphi_1_1': -0.008727652952075005, 
 'a_0': 0.6994574666023254, 
 'a_1': 0.7021579742431641}

In [37]:
create_optimized_parameters_to_print(modes=2, optimized_parameters=optimized_parameters, circuit_parameters=circuit_parameters)

{{theta_1_0}: -0.008990095928311348,
 {phi_1_0}: -1.7685526609420776,
 {varphi_1_0}: -0.00886836089193821,
 {varphi_1_1}: -0.008727652952075005,
 {a_0}: 0.6994574666023254,
 {a_1}: 0.7021579742431641}

In [9]:
[tf_alpha_0, tf_alpha_1, tf_alpha_2] = [0.6687499999999998, 0.6687499999999998, 0.6687499999999998]

In [12]:
[tf_theta_1_0, tf_theta_1_1, tf_theta_1_2, tf_phi_1_0, tf_phi_1_1, tf_phi_1_2, tf_varphi_1_0, tf_varphi_1_1, tf_varphi_1_2, tf_a_0, tf_a_1, tf_a_2] = [0.6989617347717285, -0.4482949376106262, 0.5959842205047607, -0.0008065046276897192, 0.007647479884326458, 0.0014407442649826407, -0.0009840255370363593, 0.0004724813625216484, -0.0002699749602470547, 0.6797224283218384, 0.7170392274856567, 0.6569817662239075]

In [14]:
tf_phi_1_0

-0.0008065046276897192

In [2]:
len([0.6989617347717285, -0.4482949376106262, 0.5959842205047607, -0.0008065046276897192, 0.007647479884326458, 0.0014407442649826407, -0.0009840255370363593, 0.0004724813625216484, -0.0002699749602470547, 0.6797224283218384, 0.7170392274856567, 0.6569817662239075])

12

In [ ]:
{'theta_1_0': 0.6989617347717285, 
 'theta_1_1': -0.4482949376106262, 
 'theta_1_2': 0.5959842205047607, 
 'phi_1_0': -0.0008065046276897192, 
 'phi_1_1': 0.007647479884326458, 
 'phi_1_2': 0.0014407442649826407, 
 'varphi_1_0': -0.0009840255370363593, 
 'varphi_1_1': 0.0004724813625216484, 
 'varphi_1_2': -0.0002699749602470547, 
 'a_0': 0.6797224283218384, 
 'a_1': 0.7170392274856567, 
 'a_2': 0.6569817662239075}

In [16]:
alpha_0 = tf_alpha_0
alpha_1=tf_alpha_1
alpha_2=tf_alpha_2
theta_1_0=tf_theta_1_0
theta_1_1=tf_theta_1_1
theta_1_2=tf_theta_1_2
phi_1_0=tf_phi_1_0
phi_1_1=tf_phi_1_0
phi_1_2=tf_phi_1_0
varphi_1_0=tf_varphi_1_0
varphi_1_1=tf_varphi_1_1
varphi_1_2=tf_varphi_1_2
a_0=tf_a_0
a_1=tf_a_1
a_2=tf_a_2

In [17]:
input_modes=3

In [18]:
# create an engine
# eng = sf.Engine("gaussian")
eng = sf.Engine(backend="tf", backend_options={
        "cutoff_dim": 10,
        "batch_size": None,
    })

In [19]:
# create a program
prog = sf.Program(input_modes)

alpha_0 = prog.params("alpha_0")
alpha_1 = prog.params("alpha_1")
alpha_2 = prog.params("alpha_2")
theta_1_0 = prog.params("theta_1_0")
theta_1_1 = prog.params("theta_1_1")
theta_1_2 = prog.params("theta_1_2")
phi_1_0 = prog.params("phi_1_0")
phi_1_1 = prog.params("phi_1_1")
phi_1_2 = prog.params("phi_1_2")
varphi_1_0 = prog.params("varphi_1_0")
varphi_1_1 = prog.params("varphi_1_1")
varphi_1_2 = prog.params("varphi_1_2")
a_0 = prog.params("a_0")
a_1 = prog.params("a_1")
a_2 = prog.params("a_2")

with prog.context as q:
    Dgate(alpha_0, 0) | (q[0])
    Dgate(alpha_1, 0) | (q[1])
    Dgate(alpha_2, 0) | (q[2])
    BSgate(theta_1_0, phi_1_0) | (q[0], q[1])
    BSgate(theta_1_1, phi_1_1) | (q[1], q[2])
    BSgate(theta_1_2, phi_1_2) | (q[0], q[1])
    Rgate(varphi_1_0) | (q[0])
    Rgate(varphi_1_1) | (q[1])
    Rgate(varphi_1_2) | (q[2])
    Dgate(a_0, 0) | (q[0])
    Dgate(a_1, 0) | (q[1])
    Dgate(a_2, 0) | (q[2])



In [20]:
# eng.reset()
# result = eng.run(prog)
result = eng.run(prog, args={
            "alpha_0": tf_alpha_0,
            "alpha_1": tf_alpha_1,
            "alpha_2": tf_alpha_2,
    "theta_1_0": tf_theta_1_0,
    "theta_1_1": tf_theta_1_1,
    "theta_1_2": tf_theta_1_2,
    "phi_1_0": tf_phi_1_0,
    "phi_1_1": tf_phi_1_1,
    "phi_1_2": tf_phi_1_2,
    "varphi_1_0": tf_varphi_1_0,
    "varphi_1_1": tf_varphi_1_1,
    "varphi_1_2": tf_varphi_1_2,
    "a_0": tf_a_0,
    "a_1": tf_a_1,
    "a_2": tf_a_2
        })

In [21]:
for i in range(input_modes):
    e, v = result.state.quad_expectation(mode=i)
    print(f'Mode: {i}, Expectation: {e.numpy()}, Variance: {v.numpy()}')

Mode: 0, Expectation: 0.21573884785175323, Variance: 0.9991664886474609
Mode: 1, Expectation: 3.40030837059021, Variance: 0.9949750900268555
Mode: 2, Expectation: 1.701050043106079, Variance: 1.0016653537750244


In [22]:
all_fock_probs = result.state.all_fock_probs()

In [23]:
alpha_0=0.6687499999999998
alpha_1=0.6687499999999998
alpha_2=0.6687499999999998

In [91]:
alpha_0=0.6687499999999998
alpha_1=-0.6687499999999998
alpha_2=-0.6687499999999998

In [97]:
alpha_0=-0.6687499999999998
alpha_1=0.6687499999999998
alpha_2=-0.6687499999999998

In [103]:
alpha_0=-0.6687499999999998
alpha_1=-0.6687499999999998
alpha_2=0.6687499999999998

In [25]:
eng = sf.Engine("gaussian")

In [24]:
# create a program
prog = sf.Program(input_modes)

with prog.context as q:
    Dgate(alpha_0, 0) | (q[0])
    Dgate(alpha_1, 0) | (q[1])
    Dgate(alpha_2, 0) | (q[2])
    BSgate(theta_1_0, phi_1_0) | (q[0], q[1])
    BSgate(theta_1_1, phi_1_1) | (q[1], q[2])
    BSgate(theta_1_2, phi_1_2) | (q[0], q[1])
    Rgate(varphi_1_0) | (q[0])
    Rgate(varphi_1_1) | (q[1])
    Rgate(varphi_1_2) | (q[2])
    Dgate(a_0, 0) | (q[0])
    Dgate(a_1, 0) | (q[1])
    Dgate(a_2, 0) | (q[2])

In [26]:
# eng.reset()
result = eng.run(prog)

In [27]:
means = result.state.means()

In [28]:
cov = result.state.cov()

In [29]:
import itertools

In [30]:
def generate_all_outcomes(modes=int):
    options = [0, 1]
    return [*itertools.product(options, repeat=modes)]

In [31]:
outcomes = generate_all_outcomes(3)

In [34]:
total = 0
for outcome in outcomes:
    interm = thewalrus.threshold_detection_prob(means, cov, outcome)
    total += interm
    print(f'outcome: {outcome} -> {interm}')
print(f'Total: {total}')

outcome: (0, 0, 0) -> 0.02612163226169674
outcome: (0, 0, 1) -> 0.027794974396216945
outcome: (0, 1, 0) -> 0.45274238775697906
outcome: (0, 1, 1) -> 0.48174489824051914
outcome: (1, 0, 0) -> 0.0003064630299145291
outcome: (1, 0, 1) -> 0.0003260949386517459
outcome: (1, 1, 0) -> 0.005311643718612322
outcome: (1, 1, 1) -> 0.005651905657409612
Total: 1.0000000000000002


In [96]:
total = 0
for outcome in outcomes:
    interm = thewalrus.threshold_detection_prob(means, cov, outcome)
    total += interm
    print(f'outcome: {outcome} -> {interm}')
print(f'Total: {total}')

outcome: (0, 0, 0) -> 0.03178489158974361
outcome: (0, 0, 1) -> 0.00013097359763974436
outcome: (0, 1, 0) -> 0.048009392769148625
outcome: (0, 1, 1) -> 0.00019782867195633627
outcome: (1, 0, 0) -> 0.364915896250877
outcome: (1, 0, 1) -> 0.0015036813208238564
outcome: (1, 1, 0) -> 0.5511861049250024
outcome: (1, 1, 1) -> 0.0022712308748085303
Total: 1.0000000000000002


In [102]:
total = 0
for outcome in outcomes:
    interm = thewalrus.threshold_detection_prob(means, cov, outcome)
    total += interm
    print(f'outcome: {outcome} -> {interm}')
print(f'Total: {total}')

outcome: (0, 0, 0) -> 0.2099493264269784
outcome: (0, 0, 1) -> 0.010534298366176777
outcome: (0, 1, 0) -> 0.6645379317898834
outcome: (0, 1, 1) -> 0.03334347848718367
outcome: (1, 0, 0) -> 0.018662737849755265
outcome: (1, 0, 1) -> 0.0009364109529898718
outcome: (1, 1, 0) -> 0.059071859973443
outcome: (1, 1, 1) -> 0.002963956153589964
Total: 1.0000000000000004


In [108]:
total = 0
for outcome in outcomes:
    interm = thewalrus.threshold_detection_prob(means, cov, outcome)
    total += interm
    print(f'outcome: {outcome} -> {interm}')
print(f'Total: {total}')

outcome: (0, 0, 0) -> 0.29324499107221447
outcome: (0, 0, 1) -> 0.32096519814538754
outcome: (0, 1, 0) -> 0.04206391062558518
outcome: (0, 1, 1) -> 0.046040177393468495
outcome: (1, 0, 0) -> 0.12429598819710069
outcome: (1, 0, 1) -> 0.13604558541473846
outcome: (1, 1, 0) -> 0.017829376452517476
outcome: (1, 1, 1) -> 0.01951477269898788
Total: 1.0


In [ ]:
total = 0
for outcome in outcomes:
    interm = thewalrus.threshold_detection_prob(means, cov, outcome)
    total += interm
    print(f'outcome: {outcome} -> {interm}')
print(f'Total: {total}')

In [28]:
eng = sf.Engine("gaussian")

In [55]:
alpha_0=-0.6687499999999998
alpha_1=-0.6687499999999998
theta_1_0=-0.008990096
phi_1_0=-1.7685527
varphi_1_0=-0.008868361
varphi_1_1=-0.008727653
a_0=0.69945747
a_1=0.702158

In [56]:
input_modes=2

In [57]:
prog = sf.Program(input_modes)

with prog.context as q:
    Dgate(alpha_0, 0) | (q[0])
    Dgate(alpha_1, 0) | (q[1])
    BSgate(theta_1_0, phi_1_0) | (q[0], q[1])
    Rgate(varphi_1_0) | (q[0])
    Rgate(varphi_1_1) | (q[1])
    Dgate(a_0, 0) | (q[0])
    Dgate(a_1, 0) | (q[1])

In [58]:
eng.reset()
result = eng.run(prog)

In [59]:
means = result.state.means()

In [60]:
cov = result.state.cov()

In [61]:
cov

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
means

array([ 6.37793077e-02,  6.44558090e-02,  5.05714649e-05, -9.60573901e-05])

In [33]:
import thewalrus

In [63]:
thewalrus.threshold_detection_prob(means, cov, [0,0])

0.9979465204844343

In [64]:
thewalrus.threshold_detection_prob(means, cov, [0,1])

0.001037045773001743

In [65]:
thewalrus.threshold_detection_prob(means, cov, [1,0])

0.0010153785817466727

In [66]:

thewalrus.threshold_detection_prob(means, cov, [1,1])

1.0551608173869909e-06

In [3]:
from run_test_one_codebook import execute_testing_circuit_one_codeword, create_codeword_from_binary, create_alphas
from csd.typings.typing import CutOffDimensions

In [12]:
alphas = create_alphas()
one_alpha = alphas[7]
input_modes = 3

In [13]:
one_binary_codeword = [0, 0, 0]
one_codeword = create_codeword_from_binary(binary_codeword=one_binary_codeword, one_alpha=one_alpha)
cutoff_dim = CutOffDimensions(default=10,high=15,extreme=30)

In [14]:
print(one_alpha, one_codeword)

0.6687499999999998 [0.6687499999999998, 0.6687499999999998, 0.6687499999999998]


In [10]:
optimized_parameters = [-0.008990096, -1.7685527, -0.008868361, -0.008727653, 0.69945747, 0.702158]

In [15]:
optimized_parameters = [0.6989617347717285, -0.4482949376106262, 0.5959842205047607, -0.0008065046276897192, 0.007647479884326458, 0.0014407442649826407, -0.0009840255370363593, 0.0004724813625216484, -0.0002699749602470547, 0.6797224283218384, 0.7170392274856567, 0.6569817662239075]

In [16]:
execute_testing_circuit_one_codeword(alpha_value=one_alpha,
                                         number_modes=input_modes,
                                         cutoff_dimension=cutoff_dim,
                                         one_codeword=one_codeword,
                                         optimized_parameters=optimized_parameters)

[CSD] 0.0.1|DEBUG|2022-03-19 09:10:27]: current codebook: [[0.6687499999999998, 0.6687499999999998, 0.6687499999999998]]
[CSD] 0.0.1|DEBUG|2022-03-19 09:10:27]: Going to test with the trained optimized parameters: [0.6989617347717285, -0.4482949376106262, 0.5959842205047607, -0.0008065046276897192, 0.007647479884326458, 0.0014407442649826407, -0.0009840255370363593, 0.0004724813625216484, -0.0002699749602470547, 0.6797224283218384, 0.7170392274856567, 0.6569817662239075]
[CSD] 0.0.1|DEBUG|2022-03-19 09:10:28]: TESTING Success probability from trained parameters: 0.9999995231628418
[CSD] 0.0.1|INFO|2022-03-19 09:10:28]: 

---------------------------------------------------------------------
  ALPHA:0.67 -> CODEBOOK[1/1]: 

  TOTAL computation time: 0 seconds
  Current codebook iteration time: 0 seconds
  Estimated codebook REMAINING time: 0 seconds
---------------------------------------------------------------------


[CSD] 0.0.1|DEBUG|2022-03-19 09:10:28]: pSucc: 0.9999995231628418 co

Mode: 0, Expectation: 0.21593521535396576, Variance: 0.9999996423721313
Mode: 1, Expectation: 3.4109439849853516, Variance: 0.9999761581420898
Mode: 2, Expectation: 1.7025452852249146, Variance: 1.0000004768371582
[0.6989617347717285, -0.4482949376106262, 0.5959842205047607, -0.0008065046276897192, 0.007647479884326458, 0.0014407442649826407, -0.0009840255370363593, 0.0004724813625216484, -0.0002699749602470547, 0.6797224283218384, 0.7170392274856567, 0.6569817662239075]


****************************************

CIRCUIT for alpha: 0.67 codebook_size:1 modes:3 ancillas: 0 
  cutoff_dim: [10,15,30] squeezing: False: 

Dgate({alpha_0}, 0) | (q[0])
Dgate({alpha_1}, 0) | (q[1])
Dgate({alpha_2}, 0) | (q[2])
BSgate({theta_1_0}, {phi_1_0}) | (q[0], q[1])
BSgate({theta_1_1}, {phi_1_1}) | (q[1], q[2])
BSgate({theta_1_2}, {phi_1_2}) | (q[0], q[1])
Rgate({varphi_1_0}) | (q[0])
Rgate({varphi_1_1}) | (q[1])
Rgate({varphi_1_2}) | (q[2])
Dgate({a_0}, 0) | (q[0])
Dgate({a_1}, 0) | (q[1])
Dgate({a_2},

In [5]:
eng = sf.Engine(backend="tf", backend_options={"cutoff_dim": 7})a

In [16]:

eng.reset()
prog = sf.Program(2)

with prog.context as q:
    Dgate(0.9) | q[0]
    Dgate(-0.1) | q[0]

result = eng.run(prog)
# print("Measured Homodyne sample from mode 0:", result.samples[0][0])

mean, var = result.state.mean_photon(0)
print("Mean photon number of mode 0:", mean)

mean, var = result.state.mean_photon(1)
print("Mean photon number of mode 1:", mean)

Mean photon number of mode 0: tf.Tensor(0.63983303, shape=(), dtype=float32)
Mean photon number of mode 1: tf.Tensor(0.0, shape=(), dtype=float32)


In [14]:
0.01/0.1

0.09999999999999999

In [54]:
NUM_SHOTS = 1
number_modes = 2
batch_size = 2**number_modes
alpha_val = 0.7
batch = generate_all_codewords(word_size=number_modes, alpha_value=alpha_val)

In [55]:
def single_layer(params):
    # Creates a single mode quantum "program".
    # https://strawberryfields.readthedocs.io/en/stable/code/api/strawberryfields.Program.html
    prog = sf.Program(number_modes)

    # Instantiate the Gaussian backend.
    # https://strawberryfields.readthedocs.io/en/stable/introduction/circuits.html
    eng = sf.Engine("tf", backend_options={"cutoff_dim": 5, "batch_size": batch_size})

    with prog.context as q:
        # Phase space squeezing gate.
        # https://strawberryfields.readthedocs.io/en/stable/code/api/strawberryfields.ops.Sgate.html
        sf.ops.Dgate(params["displacement_magnitude"])  | q[0]
        sf.ops.Dgate(params["displacement_magnitude"])  | q[1]

        # Measures whether a mode contains zero or nonzero photons.
        # https://strawberryfields.readthedocs.io/en/stable/code/api/strawberryfields.ops.MeasureThreshold.html
        sf.ops.MeasureFock()                       | q

    return eng.run(prog, shots=NUM_SHOTS)

In [56]:
# Parameters
params = {
    "displacement_magnitude": 0.5
}

In [57]:
# Execute the single layer of the quantum "program".
result = single_layer(params=params)

In [58]:
# Obtain results.
print(result.samples)

tf.Tensor(
[[[0 0]]

 [[0 0]]

 [[0 1]]

 [[0 0]]], shape=(4, 1, 2), dtype=int32)


In [60]:
[print(sample) for sample in result.samples]

tf.Tensor([[0 0]], shape=(1, 2), dtype=int32)
tf.Tensor([[0 0]], shape=(1, 2), dtype=int32)
tf.Tensor([[0 1]], shape=(1, 2), dtype=int32)
tf.Tensor([[0 0]], shape=(1, 2), dtype=int32)


[None, None, None, None]

In [61]:
one_sample = result.samples[0]

In [70]:
one_sample[0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 0], dtype=int32)>

In [72]:
convert_batch_sampling_output_to_codeword_list(alpha_value=0.5, batch_samples=result.samples)

tf.Tensor([[0 0]], shape=(1, 2), dtype=int32)
[0.5, 0.5]
tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)
tf.Tensor([[0 0]], shape=(1, 2), dtype=int32)
[0.5, 0.5]
tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)
tf.Tensor([[0 1]], shape=(1, 2), dtype=int32)
[0.5, -0.5]
tf.Tensor([ 0.5 -0.5], shape=(2,), dtype=float32)
tf.Tensor([[0 0]], shape=(1, 2), dtype=int32)
[0.5, 0.5]
tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)


[tf.Tensor([0.5 0.5], shape=(2,), dtype=float32),
 tf.Tensor([0.5 0.5], shape=(2,), dtype=float32),
 tf.Tensor([ 0.5 -0.5], shape=(2,), dtype=float32),
 tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)]

In [66]:
def convert_batch_sampling_output_to_codeword_list(alpha_value: float, batch_samples) -> List[CodeWord]:
    return [convert_sampling_output_to_codeword(alpha_value=alpha_value, one_codeword_output=one_codeword_output) for one_codeword_output in batch_samples]

In [71]:
def convert_sampling_output_to_codeword(alpha_value: float, one_codeword_output) -> CodeWord:
    ON = -1
    OFF = 1
    print(one_codeword_output)
    word = [alpha_value * (ON if one_mode_output != 0 else OFF) for one_mode_output in one_codeword_output[0]]
    print(word)
    tf_word=tf.constant(word)
    cw = CodeWord(word=tf_word)
    print(cw)
    return cw


In [11]:
codeword = convert_sampling_output_to_codeword(alpha_value=0.5, 
                                               tf_samples=result.samples)

tf.Tensor([0 0], shape=(2,), dtype=int64)
[0.5, 0.5]
tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)


In [12]:
print(codeword)

tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)


In [13]:
results = [single_layer(params=params).samples for _ in range(100)]

In [14]:
codewords = [convert_sampling_output_to_codeword(alpha_value=0.5, 
                                               tf_samples=result) for result in results]

tf.Tensor([2 0], shape=(2,), dtype=int64)
[-0.5, 0.5]
tf.Tensor([-0.5  0.5], shape=(2,), dtype=float32)
tf.Tensor([2 0], shape=(2,), dtype=int64)
[-0.5, 0.5]
tf.Tensor([-0.5  0.5], shape=(2,), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
[-0.5, 0.5]
tf.Tensor([-0.5  0.5], shape=(2,), dtype=float32)
tf.Tensor([0 0], shape=(2,), dtype=int64)
[0.5, 0.5]
tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)
tf.Tensor([0 0], shape=(2,), dtype=int64)
[0.5, 0.5]
tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)
tf.Tensor([0 1], shape=(2,), dtype=int64)
[0.5, -0.5]
tf.Tensor([ 0.5 -0.5], shape=(2,), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
[-0.5, 0.5]
tf.Tensor([-0.5  0.5], shape=(2,), dtype=float32)
tf.Tensor([0 0], shape=(2,), dtype=int64)
[0.5, 0.5]
tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)
tf.Tensor([0 0], shape=(2,), dtype=int64)
[0.5, 0.5]
tf.Tensor([0.5 0.5], shape=(2,), dtype=float32)
tf.Tensor([0 1], shape=(2,), dtype=int64)
[0.5, -0.5]
tf.Tensor([ 0.5 -0.5],

In [139]:
one_result = results[0][0]

In [148]:
one_result

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>

In [152]:
tf_alpha = tf.constant(([alpha_value, alpha_value]))

In [154]:
tf.math.multiply(one_result,tf_alpha)

InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a int64 tensor but is a float tensor [Op:Mul]

In [155]:
alpha_value = 0.5
ON = -1
OFF = 1
word = [alpha_value * (ON if sample != 0 else OFF) for sample in one_result]

In [158]:
tf.constant(word)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5, 0.5], dtype=float32)>

In [52]:
import os
import tensorflow as tf
import random
from typing import List
import itertools
os.environ["TF_FORCE_GPU_ALLOW_GROWTH"] = "true"

In [53]:
def generate_all_codewords(word_size: int, alpha_value: float) -> List[List[float]]:
    letters = [alpha_value, -alpha_value]
    codewords = [CodeWord(size=len(word), alpha_value=alpha_value, word=list(word))
            for word in itertools.product(letters, repeat=word_size)]
    return [codeword.word for codeword in codewords]

In [50]:

tf_b1 = tf.Variable(0.1)
tf_b2 = tf.Variable(0.1)

opt = tf.keras.optimizers.Adam(learning_rate=0.01)
steps = 40

number_modes = 2
batch_size = 2**number_modes
alpha_val = 0.7
batch = generate_all_codewords(word_size=number_modes, alpha_value=alpha_val)
print(batch)
for step in range(steps):    
    eng = sf.Engine(backend="tf", backend_options={
        "cutoff_dim": 7,
        "batch_size": batch_size,
    })
    
    circuit = sf.Program(number_modes)
    
    b1 = circuit.params("b1")
    b2 = circuit.params("b2")
    alpha1 = circuit.params("alpha1")
    alpha2 = circuit.params("alpha2")

    with circuit.context as q:
        sf.ops.Dgate(alpha1, 0.0) | q[0]
        sf.ops.Dgate(alpha2, 0.0) | q[1]
        sf.ops.Dgate(b1, 0.0) | q[0]
        sf.ops.Dgate(b2, 0.0) | q[1]
        sf.ops.MeasureFock()  | q
        
    with tf.GradientTape() as tape:
        results = eng.run(circuit, args={
            "alpha1": alpha_val,
            "alpha2": alpha_val,
            "b1": tf_b1,
            "b2": tf_b2
        })
        print(f"Result samples: {result.samples}")
        codeword = convert_sampling_output_to_codeword(alpha_value=alpha_val, 
                                               tf_samples=result.samples)
        
        print(f"codeword: {codeword}")
        # get the probability of |0>
        p_zero = results.state.fock_prob([0])
        print(f"p_zero: {p_zero}")
        print(f"bach_size: {batch_size}")
                
        loss /= p_zero/batch_size
        print(f"loss: {loss}")
        
    gradients = tape.gradient(loss, [tf_b1, tf_b2])
    opt.apply_gradients(zip(gradients, [tf_b1,tf_b2]))
    
    if (step + 1) % 10 == 0:
        print("Learned displacement value at step {}: {}".format(step+1, tf_displacement_magnitude.numpy()))

[[0.7, 0.7], [0.7, -0.7], [-0.7, 0.7], [-0.7, -0.7]]
Result samples: [[[0 0]]

 [[0 0]]

 [[1 0]]

 [[0 0]]]
tf.Tensor([[0 0]], shape=(1, 2), dtype=int32)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()