In [1]:
from csd import CSD
from csd.typings import CSDConfiguration, Backends, RunConfiguration, MeasuringTypes
import numpy as np

In [6]:
valid_backends = [
    Backends.FOCK,
    Backends.GAUSSIAN,
    Backends.TENSORFLOW,
]

# alphas = np.arange(0.4, 1.4, 0.1)
alphas = [0.7]
betas = list(np.arange(0.0, 1.1, 0.1))

In [11]:
run_configuration = RunConfiguration({
        'alphas': alphas,
        'params': {
            'betas': betas,
        },
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES,
        'codeword_size': 10,
        'cutoff_dim': 2
    })

In [12]:
CSD().execute(configuration=run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-11 10:15:04]: Executing One Layer circuit with Backend: fock, codeword: [0.7, -0.7, 0.7, 0.7, 0.7, 0.7, -0.7, -0.7, 0.7, 0.7] beta values: [0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0] with measuring_type: probabilities


[{'alpha': 0.7,
  'codeword': [0.7, -0.7, 0.7, 0.7, 0.7, 0.7, -0.7, -0.7, 0.7, 0.7],
  'betas': [0.0,
   0.1,
   0.2,
   0.30000000000000004,
   0.4,
   0.5,
   0.6000000000000001,
   0.7000000000000001,
   0.8,
   0.9,
   1.0],
  'p_err': [0.24494944232623356,
   0.29544922559057574,
   0.3455327962421446,
   0.39255528828295744,
   0.43437080202834616,
   0.4694841016325956,
   0.49711218446762684,
   0.5171575111128872,
   0.5301078091173871,
   0.5368863696735715,
   0.5386804935965188]}]

In [13]:
run_configuration = RunConfiguration({
        'alphas': alphas,
        'params': {
            'betas': betas,
        },
        'backend': Backends.GAUSSIAN,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES,
        'codeword_size': 10,
        'cutoff_dim': 2
    })

In [14]:
CSD().execute(configuration=run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-11 10:16:36]: Executing One Layer circuit with Backend: gaussian, codeword: [0.7, -0.7, -0.7, 0.7, 0.7, 0.7, 0.7, -0.7, 0.7, 0.7] beta values: [0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0] with measuring_type: probabilities


[{'alpha': 0.7,
  'codeword': [0.7, -0.7, -0.7, 0.7, 0.7, 0.7, 0.7, -0.7, 0.7, 0.7],
  'betas': [0.0,
   0.1,
   0.2,
   0.30000000000000004,
   0.4,
   0.5,
   0.6000000000000001,
   0.7000000000000001,
   0.8,
   0.9,
   1.0],
  'p_err': [0.24494944232623356,
   0.294417581565299,
   0.34211161802718515,
   0.3864320148329523,
   0.42613713975376577,
   0.46037644776946945,
   0.48868991828086034,
   0.5109793737486878,
   0.5274588650021115,
   0.5385917267064924,
   0.5450214624947838]}]

In [15]:
run_configuration = RunConfiguration({
        'alphas': alphas,
        'params': {
            'betas': betas,
        },
        'backend': Backends.TENSORFLOW,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES,
        'codeword_size': 10,
        'cutoff_dim': 2
    })

In [16]:
CSD().execute(configuration=run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-11 10:17:20]: Executing One Layer circuit with Backend: tf, codeword: [-0.7, -0.7, 0.7, 0.7, 0.7, 0.7, -0.7, -0.7, 0.7, -0.7] beta values: [0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0] with measuring_type: probabilities


[{'alpha': 0.7,
  'codeword': [-0.7, -0.7, 0.7, 0.7, 0.7, 0.7, -0.7, -0.7, 0.7, -0.7],
  'betas': [0.0,
   0.1,
   0.2,
   0.30000000000000004,
   0.4,
   0.5,
   0.6000000000000001,
   0.7000000000000001,
   0.8,
   0.9,
   1.0],
  'p_err': [<tf.Tensor: shape=(), dtype=float32, numpy=0.25>,
   <tf.Tensor: shape=(), dtype=float32, numpy=0.29245716>,
   <tf.Tensor: shape=(), dtype=float32, numpy=0.33240467>,
   <tf.Tensor: shape=(), dtype=float32, numpy=0.36757863>,
   <tf.Tensor: shape=(), dtype=float32, numpy=0.39617276>,
   <tf.Tensor: shape=(), dtype=float32, numpy=0.41698986>,
   <tf.Tensor: shape=(), dtype=float32, numpy=0.42951423>,
   <tf.Tensor: shape=(), dtype=float32, numpy=0.4339024>,
   <tf.Tensor: shape=(), dtype=float32, numpy=0.4308986>,
   <tf.Tensor: shape=(), dtype=float32, numpy=0.421695>,
   <tf.Tensor: shape=(), dtype=float32, numpy=0.40776086>]}]

In [17]:
run_configuration = RunConfiguration({
        'alphas': alphas,
        'params': {
            'betas': betas,
        },
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.SAMPLING,
        'shots': 100,
        'codeword_size': 10,
        'cutoff_dim': 2
    })

In [18]:
CSD().execute(configuration=run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-11 10:18:07]: Executing One Layer circuit with Backend: fock, codeword: [-0.7, 0.7, 0.7, 0.7, 0.7, -0.7, -0.7, -0.7, -0.7, -0.7] beta values: [0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0] with measuring_type: sampling


[{'alpha': 0.7,
  'codeword': [-0.7, 0.7, 0.7, 0.7, 0.7, -0.7, -0.7, -0.7, -0.7, -0.7],
  'betas': [0.0,
   0.1,
   0.2,
   0.30000000000000004,
   0.4,
   0.5,
   0.6000000000000001,
   0.7000000000000001,
   0.8,
   0.9,
   1.0],
  'p_err': [0.305,
   0.35200000000000004,
   0.392,
   0.42960000000000004,
   0.45380000000000004,
   0.4688,
   0.4838000000000001,
   0.47400000000000003,
   0.4578000000000001,
   0.4366,
   0.41100000000000003]}]

In [19]:
run_configuration = RunConfiguration({
        'alphas': alphas,
        'params': {
            'betas': betas,
        },
        'backend': Backends.TENSORFLOW,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.SAMPLING,
        'shots': 100,
        'codeword_size': 10,
        'cutoff_dim': 2
    })

In [20]:
CSD().execute(configuration=run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-11 10:19:01]: Executing One Layer circuit with Backend: tf, codeword: [0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, -0.7, 0.7, 0.7] beta values: [0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6000000000000001, 0.7000000000000001, 0.8, 0.9, 1.0] with measuring_type: sampling


[{'alpha': 0.7,
  'codeword': [0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, -0.7, 0.7, 0.7],
  'betas': [0.0,
   0.1,
   0.2,
   0.30000000000000004,
   0.4,
   0.5,
   0.6000000000000001,
   0.7000000000000001,
   0.8,
   0.9,
   1.0],
  'p_err': [0.2425,
   0.30649999999999994,
   0.326,
   0.3785,
   0.4040000000000001,
   0.4245,
   0.4415,
   0.4374999999999999,
   0.42699999999999994,
   0.417,
   0.4125]}]