In [1]:
from csd import CSD
from csd.typings import CSDConfiguration, Backends, RunConfiguration, MeasuringTypes
import numpy as np

In [2]:
valid_backends = [
    Backends.FOCK,
    Backends.GAUSSIAN,
    Backends.TENSORFLOW,
]

# alphas = np.arange(0.4, 1.4, 0.1)
alphas = [0.7]
betas = np.arange(0.0, 1.1, 0.1)

In [9]:
run_configuration = RunConfiguration({
        'alpha': 0.7,
        'displacement_magnitude': 0.2,
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES,
        'codeword_size': 100,
        'cutoff_dim': 7
    })

In [10]:
CSD().execute(configuration=run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-10 12:13:27]: Executing One Layer circuit with Backend: fock, codeword: [-0.7, 0.7, -0.7, -0.7, 0.7, 0.7, -0.7, -0.7, 0.7, 0.7, -0.7, 0.7, 0.7, -0.7, 0.7, -0.7, -0.7, 0.7, -0.7, -0.7, -0.7, 0.7, -0.7, -0.7, 0.7, 0.7, -0.7, -0.7, -0.7, -0.7, -0.7, 0.7, 0.7, -0.7, 0.7, 0.7, 0.7, 0.7, -0.7, -0.7, -0.7, 0.7, 0.7, 0.7, -0.7, 0.7, 0.7, -0.7, -0.7, -0.7, -0.7, -0.7, -0.7, 0.7, -0.7, 0.7, 0.7, 0.7, -0.7, 0.7, -0.7, 0.7, 0.7, -0.7, -0.7, 0.7, -0.7, -0.7, -0.7, -0.7, -0.7, 0.7, 0.7, 0.7, -0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, -0.7, -0.7, 0.7, 0.7, -0.7, 0.7, -0.7, 0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, 0.7, 0.7, -0.7, -0.7, 0.7] beta: 0.2 with measuring_type: probabilities


0.5128526560425721

In [11]:
CSD().execute(configuration=run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-10 12:13:28]: Executing One Layer circuit with Backend: fock, codeword: [0.7, -0.7, 0.7, 0.7, 0.7, -0.7, 0.7, -0.7, -0.7, 0.7, -0.7, -0.7, 0.7, -0.7, 0.7, 0.7, -0.7, 0.7, 0.7, 0.7, -0.7, -0.7, 0.7, 0.7, -0.7, 0.7, 0.7, -0.7, 0.7, -0.7, -0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, 0.7, 0.7, 0.7, -0.7, 0.7, 0.7, 0.7, -0.7, -0.7, -0.7, -0.7, -0.7, 0.7, -0.7, -0.7, -0.7, 0.7, -0.7, -0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, 0.7, 0.7, -0.7, -0.7, -0.7, -0.7, 0.7, 0.7, -0.7, 0.7, 0.7, -0.7, 0.7, 0.7, 0.7, 0.7, 0.7, -0.7, -0.7, 0.7, 0.7, -0.7, 0.7, -0.7, 0.7, 0.7, -0.7, -0.7, 0.7, 0.7, -0.7, 0.7, -0.7, -0.7, -0.7, -0.7, -0.7, 0.7] beta: 0.2 with measuring_type: probabilities


0.5023033770354342

In [12]:
[CSD().execute(configuration = RunConfiguration({
        'alpha': 0.7,
        'displacement_magnitude': beta,
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES,
        'codeword_size': 100,
        'cutoff_dim': 2
    })) for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-10 12:13:44]: Executing One Layer circuit with Backend: fock, codeword: [0.7, 0.7, -0.7, -0.7, -0.7, -0.7, 0.7, -0.7, 0.7, 0.7, 0.7, 0.7, -0.7, 0.7, -0.7, -0.7, -0.7, -0.7, -0.7, 0.7, -0.7, -0.7, -0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, 0.7, 0.7, 0.7, -0.7, -0.7, -0.7, -0.7, 0.7, -0.7, -0.7, -0.7, -0.7, -0.7, 0.7, 0.7, -0.7, 0.7, -0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, -0.7, 0.7, 0.7, -0.7, 0.7, 0.7, -0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, 0.7, 0.7, -0.7, 0.7, 0.7, -0.7, 0.7, 0.7, -0.7, 0.7, -0.7, 0.7, -0.7, -0.7, -0.7, 0.7, 0.7, 0.7, -0.7, -0.7, 0.7, -0.7, 0.7, 0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, -0.7, 0.7, -0.7, 0.7] beta: 0.0 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 12:13:44]: Executing One Layer circuit with Backend: fock, codeword: [0.7, -0.7, -0.7, 0.7, 0.7, 0.7, 0.7, 0.7, -0.7, -0.7, 0.7, 0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, 0.7, 0.7, 0.7, -0.7, -0.7, 0.7, 0.7, -0.7, -0.7, 0.7, -0.7, -0.7, 0.7, -0.7, -0.7, 0.7, -0.7, 0.7, -0.7, 0.

[0.5045050557673764,
 0.4957557564699673,
 0.5042693601097779,
 0.5,
 0.5029867196423404,
 0.49978376039141054,
 0.5033091928339213,
 0.5181406851473184,
 0.5,
 0.494078183914555,
 0.4806678498709472]

In [42]:
[CSD().execute(configuration = RunConfiguration({
        'alpha': alpha,
        'displacement_magnitude': beta,
        'backend': Backends.GAUSSIAN,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES,
        'codeword_size': 1,
        'cutoff_dim': 2
    })) for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-10 11:54:41]: Executing One Layer circuit with Backend: gaussian, codeword: [0.7] beta: 0.0 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:41]: Executing One Layer circuit with Backend: gaussian, codeword: [-0.7] beta: 0.1 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:41]: Executing One Layer circuit with Backend: gaussian, codeword: [-0.7] beta: 0.2 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:41]: Executing One Layer circuit with Backend: gaussian, codeword: [0.7] beta: 0.30000000000000004 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:41]: Executing One Layer circuit with Backend: gaussian, codeword: [-0.7] beta: 0.4 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:41]: Executing One Layer circuit with Backend: gaussian, codeword: [-0.7] beta: 0.5 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:41]: Executing One Layer ci

[0.387373605815584,
 0.697676326071031,
 0.778800783071405,
 0.6321205588285577,
 0.9139311852712283,
 0.9607894391523233,
 0.9900498337491681,
 1.0,
 0.8946007754381357,
 0.9607894391523231,
 0.944423787388517]

In [43]:
[CSD().execute(configuration = RunConfiguration({
        'alpha': alpha,
        'displacement_magnitude': beta,
        'backend': Backends.TENSORFLOW,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES,
        'codeword_size': 1,
        'cutoff_dim': 2
    })) for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-10 11:54:52]: Executing One Layer circuit with Backend: tf, codeword: [0.7] beta: 0.0 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:52]: Executing One Layer circuit with Backend: tf, codeword: [-0.7] beta: 0.1 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:52]: Executing One Layer circuit with Backend: tf, codeword: [0.7] beta: 0.2 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:52]: Executing One Layer circuit with Backend: tf, codeword: [-0.7] beta: 0.30000000000000004 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:52]: Executing One Layer circuit with Backend: tf, codeword: [-0.7] beta: 0.4 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:52]: Executing One Layer circuit with Backend: tf, codeword: [-0.7] beta: 0.5 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-10 11:54:52]: Executing One Layer circuit with Backend: tf, codeword: [0

[<tf.Tensor: shape=(), dtype=float32, numpy=0.38737357>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.69441694>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5646677>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.81974715>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.8553197>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.86954>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.8562176>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.8332281>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.78613365>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.72408974>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9797165>]

In [17]:
run_configuration = RunConfiguration({
        'alpha': 0.7,
        'displacement_magnitude': 0,
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.SAMPLING,
        'shots': 1000
    })

In [18]:
CSD().execute(configuration=run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-08 17:22:39]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0 with measuring_type: sampling


0.625

In [21]:
[CSD().execute(configuration = RunConfiguration({
        'alpha': alpha,
        'displacement_magnitude': beta,
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.SAMPLING,
        'shots': 100
    })) for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-08 17:30:20]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.0 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:20]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.1 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:20]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.2 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:20]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.30000000000000004 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:20]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.4 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:21]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.5 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:21]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.6000000000000001 with measuring_type: sampl

[0.65, 0.62, 0.47, 0.36, 0.32, 0.27, 0.15, 0.17, 0.13, 0.08]

In [22]:
[CSD().execute(configuration = RunConfiguration({
        'alpha': alpha,
        'displacement_magnitude': beta,
        'backend': Backends.TENSORFLOW,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.SAMPLING,
        'shots': 100
    })) for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-08 17:30:33]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.0 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:33]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.1 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:33]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.2 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:34]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.30000000000000004 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:34]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.4 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:34]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.5 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-08 17:30:34]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.6000000000000001 with measuring_type: sampling
[CSD] 0.0.

[0.62, 0.51, 0.37, 0.41, 0.38, 0.24, 0.18, 0.08, 0.09, 0.05]