In [1]:
from csd import CSD
from csd.typings import CSDConfiguration, Backends, RunConfiguration, MeasuringTypes
import numpy as np

In [2]:
valid_backends = [
    Backends.FOCK,
    Backends.GAUSSIAN,
    Backends.TENSORFLOW,
]

# alphas = np.arange(0.4, 1.4, 0.1)
alphas = [0.7]
betas = np.arange(0.0, 1.0, 0.1)

In [3]:
run_configuration = RunConfiguration({
        'alpha': 0.7,
        'displacement_magnitude': 0.0,
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES
    })

In [4]:
CSD().execute(configuration=run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-07 18:40:31]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.0 with measuring_type: probabilities


0.612626394184416

In [6]:
[CSD().execute(configuration = RunConfiguration({
        'alpha': alpha,
        'displacement_magnitude': beta,
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES
    })) for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-07 18:06:56]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.0 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:06:56]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.1 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:06:56]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.2 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:06:56]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.30000000000000004 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:06:56]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.4 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:06:56]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.5 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:06:56]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.6000000000000

[0.612626394184416,
 0.5272924240448807,
 0.4448580664333042,
 0.3678794443319496,
 0.29819729983859644,
 0.23692784090868343,
 0.1845197680245963,
 0.14085900379873356,
 0.10540040587080655,
 0.07730684234519926]

In [7]:
[CSD().execute(configuration = RunConfiguration({
        'alpha': alpha,
        'displacement_magnitude': beta,
        'backend': Backends.GAUSSIAN,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES
    })) for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-07 18:07:27]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 beta: 0.0 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:27]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 beta: 0.1 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:27]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 beta: 0.2 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:27]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 beta: 0.30000000000000004 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:27]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 beta: 0.4 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:27]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 beta: 0.5 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:27]: Executing One Layer circuit with Backend: gaussian, alph

[0.612626394184416,
 0.5272924240430485,
 0.4448580662229413,
 0.36787944117144233,
 0.2981972794298874,
 0.2369277586821218,
 0.1845195239929892,
 0.14085842092104503,
 0.10539922456186435,
 0.07730474044329971]

In [8]:
[CSD().execute(configuration = RunConfiguration({
        'alpha': alpha,
        'displacement_magnitude': beta,
        'backend': Backends.TENSORFLOW,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.PROBABILITIES
    })) for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-07 18:07:40]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.0 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:40]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.1 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:40]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.2 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:40]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.30000000000000004 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:40]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.4 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:40]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.5 with measuring_type: probabilities
[CSD] 0.0.1|DEBUG|2021-10-07 18:07:40]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.6000000000000001 with measu

[<tf.Tensor: shape=(), dtype=float32, numpy=0.6126264>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.52729243>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.44485798>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.3678793>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.2981973>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.23692787>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.18451975>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.140859>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.105400406>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.07730688>]

In [13]:
run_configuration = RunConfiguration({
        'alpha': 0.7,
        'displacement_magnitude': 0,
        'backend': Backends.TENSORFLOW,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.SAMPLING,
        'shots': 1000
    })

In [14]:
CSD().execute(configuration=run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-07 18:41:36]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0 with measuring_type: sampling


0.626

In [15]:
[CSD().execute(configuration = RunConfiguration({
        'alpha': alpha,
        'displacement_magnitude': beta,
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.SAMPLING,
        'shots': 1000
    })) for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-07 18:41:43]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.0 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:41:44]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.1 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:41:45]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.2 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:41:45]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.30000000000000004 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:41:46]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.4 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:41:47]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.5 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:41:47]: Executing One Layer circuit with Backend: fock, alpha: 0.7 beta: 0.6000000000000001 with measuring_type: sampl

[0.596, 0.517, 0.441, 0.375, 0.301, 0.227, 0.175, 0.159, 0.106, 0.081]

In [17]:
[CSD().execute(configuration = RunConfiguration({
        'alpha': alpha,
        'displacement_magnitude': beta,
        'backend': Backends.TENSORFLOW,
        'number_qumodes': 1,
        'number_layers': 1,
        'measuring_type': MeasuringTypes.SAMPLING,
        'shots': 1000
    })) for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-07 18:42:12]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.0 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:42:14]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.1 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:42:17]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.2 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:42:19]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.30000000000000004 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:42:21]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.4 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:42:23]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.5 with measuring_type: sampling
[CSD] 0.0.1|DEBUG|2021-10-07 18:42:26]: Executing One Layer circuit with Backend: tf, alpha: 0.7 beta: 0.6000000000000001 with measuring_type: sampling
[CSD] 0.0.

[0.622, 0.535, 0.442, 0.362, 0.259, 0.238, 0.178, 0.132, 0.12, 0.086]