In [1]:
from csd import CSD
from csd.typings import CSDConfiguration, Backends, RunConfiguration
import numpy as np

In [2]:
initial_configuration = CSDConfiguration({
        'displacement_magnitude': 0.1,
        'steps': 500,
        'learning_rate': 0.01,
        'batch_size': 10,
        'threshold': 0.5 })

In [3]:
csd = CSD(csd_config=initial_configuration)

In [4]:
result = csd.single_layer(backend=Backends.TENSORFLOW)

In [5]:
csd.show_result()

{'result': '<Result: shots=1, num_modes=1, contains state=True>',
 'state': "<FockStateTF: num_modes=1, cutoff=5, pure=True, batched=False, hbar=2, dtype=<dtype: 'complex64'>>",
 'trace': <tf.Tensor: shape=(), dtype=complex64, numpy=(1+0j)>,
 'density_matrix': <tf.Tensor: shape=(5, 5), dtype=complex64, numpy=
 array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex64)>,
 'dm_shape': TensorShape([5, 5]),
 'samples': <tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[0]])>,
 'first_sample': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0])>,
 'fock_probability': <tf.Tensor: shape=(), dtype=float32, numpy=1.0>}

In [3]:
valid_backends = [
    Backends.FOCK,
    Backends.GAUSSIAN,
    Backends.TENSORFLOW,
]

alphas = np.arange(0.4, 1.4, 0.1)
betas = np.arange(0.0, 1.0, 0.1)

In [6]:
run_configuration = RunConfiguration({
        'alpha': 0.5,
        'displacement_magnitude': 0.1,
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1
    })

In [5]:
def create_csd_and_show_prob(configuration: RunConfiguration) -> float:
    return CSD().execute(configuration).state.fock_prob([0])


In [21]:
create_csd_and_show_prob(configuration = run_configuration)

[CSD] 0.0.1|DEBUG|2021-10-06 09:41:32]: Executing One Layer circuit with Backend: fock, alpha: 0.5 and beta: 0.1


0.9999999999999998

In [6]:
[create_csd_and_show_prob(configuration = RunConfiguration({
        'alpha': 0.7,
        'displacement_magnitude': beta,
        'backend': Backends.FOCK,
        'number_qumodes': 1,
        'number_layers': 1
    })) for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-06 10:02:35]: Executing One Layer circuit with Backend: fock, alpha: 0.7 and beta: 0.0
[CSD] 0.0.1|DEBUG|2021-10-06 10:02:36]: Executing One Layer circuit with Backend: fock, alpha: 0.7 and beta: 0.1
[CSD] 0.0.1|DEBUG|2021-10-06 10:02:36]: Executing One Layer circuit with Backend: fock, alpha: 0.7 and beta: 0.2
[CSD] 0.0.1|DEBUG|2021-10-06 10:02:36]: Executing One Layer circuit with Backend: fock, alpha: 0.7 and beta: 0.30000000000000004
[CSD] 0.0.1|DEBUG|2021-10-06 10:02:36]: Executing One Layer circuit with Backend: fock, alpha: 0.7 and beta: 0.4
[CSD] 0.0.1|DEBUG|2021-10-06 10:02:36]: Executing One Layer circuit with Backend: fock, alpha: 0.7 and beta: 0.5
[CSD] 0.0.1|DEBUG|2021-10-06 10:02:36]: Executing One Layer circuit with Backend: fock, alpha: 0.7 and beta: 0.6000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 10:02:36]: Executing One Layer circuit with Backend: fock, alpha: 0.7 and beta: 0.7000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 10:02:36]: Executing 

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9999999999999998, 1.0]

In [8]:
[create_csd_and_show_prob(configuration = RunConfiguration({
        'alpha': 0.7,
        'displacement_magnitude': beta,
        'backend': Backends.TENSORFLOW,
        'number_qumodes': 1,
        'number_layers': 1
    })) for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-06 10:06:21]: Executing One Layer circuit with Backend: tf, alpha: 0.7 and beta: 0.0
[CSD] 0.0.1|DEBUG|2021-10-06 10:06:21]: Executing One Layer circuit with Backend: tf, alpha: 0.7 and beta: 0.1
[CSD] 0.0.1|DEBUG|2021-10-06 10:06:21]: Executing One Layer circuit with Backend: tf, alpha: 0.7 and beta: 0.2
[CSD] 0.0.1|DEBUG|2021-10-06 10:06:21]: Executing One Layer circuit with Backend: tf, alpha: 0.7 and beta: 0.30000000000000004
[CSD] 0.0.1|DEBUG|2021-10-06 10:06:21]: Executing One Layer circuit with Backend: tf, alpha: 0.7 and beta: 0.4
[CSD] 0.0.1|DEBUG|2021-10-06 10:06:21]: Executing One Layer circuit with Backend: tf, alpha: 0.7 and beta: 0.5
[CSD] 0.0.1|DEBUG|2021-10-06 10:06:21]: Executing One Layer circuit with Backend: tf, alpha: 0.7 and beta: 0.6000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 10:06:21]: Executing One Layer circuit with Backend: tf, alpha: 0.7 and beta: 0.7000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 10:06:21]: Executing One Layer circui

[<tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>]

In [15]:
[create_csd_and_show_prob(configuration = RunConfiguration({
        'alpha': 0.7,
        'displacement_magnitude': beta,
        'backend': Backends.GAUSSIAN,
        'number_qumodes': 1,
        'number_layers': 1
    })) for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-06 10:12:02]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.0
[CSD] 0.0.1|DEBUG|2021-10-06 10:12:02]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.1
[CSD] 0.0.1|DEBUG|2021-10-06 10:12:02]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.2
[CSD] 0.0.1|DEBUG|2021-10-06 10:12:02]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.30000000000000004
[CSD] 0.0.1|DEBUG|2021-10-06 10:12:02]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.4
[CSD] 0.0.1|DEBUG|2021-10-06 10:12:02]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.5
[CSD] 0.0.1|DEBUG|2021-10-06 10:12:02]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.6000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 10:12:02]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.7000000000000001
[CSD] 0.0.1|DEBUG|

[0.612626394184416,
 0.5272924240430485,
 0.4448580662229413,
 0.36787944117144233,
 0.2981972794298874,
 0.2369277586821218,
 0.1845195239929892,
 0.14085842092104503,
 0.10539922456186435,
 0.07730474044329971]

In [27]:
[create_csd_and_show_prob(configuration = RunConfiguration({
        'alpha': alpha,
        'displacement_magnitude': beta,
        'backend': backend,
        'number_qumodes': 1,
        'number_layers': 1
    })) for backend in valid_backends for alpha in alphas for beta in betas]

[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.4 and beta: 0.0
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.4 and beta: 0.1
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.4 and beta: 0.2
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.4 and beta: 0.30000000000000004
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.4 and beta: 0.4
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.4 and beta: 0.5
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.4 and beta: 0.6000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.4 and beta: 0.7000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing 

[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.9999999999999999 and beta: 0.7000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.9999999999999999 and beta: 0.8
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 0.9999999999999999 and beta: 0.9
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 1.0999999999999999 and beta: 0.0
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 1.0999999999999999 and beta: 0.1
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 1.0999999999999999 and beta: 0.2
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: fock, alpha: 1.0999999999999999 and beta: 0.30000000000000004
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with 

[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.2
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.30000000000000004
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.4
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.5
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.6000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.7000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.8
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 0.7 and beta: 0.9
[CSD] 0.0.1|DEBUG|

[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 1.2999999999999998 and beta: 0.30000000000000004
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 1.2999999999999998 and beta: 0.4
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 1.2999999999999998 and beta: 0.5
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 1.2999999999999998 and beta: 0.6000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 1.2999999999999998 and beta: 0.7000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 1.2999999999999998 and beta: 0.8
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: gaussian, alpha: 1.2999999999999998 and beta: 0.9
[CSD] 0.0.1|DEBUG|2021-10-06 0

[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: tf, alpha: 0.9999999999999999 and beta: 0.0
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: tf, alpha: 0.9999999999999999 and beta: 0.1
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: tf, alpha: 0.9999999999999999 and beta: 0.2
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: tf, alpha: 0.9999999999999999 and beta: 0.30000000000000004
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: tf, alpha: 0.9999999999999999 and beta: 0.4
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: tf, alpha: 0.9999999999999999 and beta: 0.5
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: tf, alpha: 0.9999999999999999 and beta: 0.6000000000000001
[CSD] 0.0.1|DEBUG|2021-10-06 09:50:16]: Executing One Layer circuit with Backend: tf, a

[1.0,
 0.9999999999999998,
 1.0,
 1.0,
 1.0,
 0.9999999999999998,
 0.9999999999999998,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9999999999999998,
 1.0,
 1.0,
 1.0,
 0.9999999999999998,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9999999999999998,
 1.0,
 0.9999999999999998,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9999999999999998,
 1.0,
 0.9999999999999998,
 1.0,
 1.0,
 0.9999999999999998,
 0.9999999999999998,
 1.0,
 1.0,
 1.0,
 0.9999999999999998,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9999999999999998,
 0.9999999999999998,
 0.9999999999999998,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9999999999999998,
 0.9999999999999998,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9999999999999998,
 0.9999999999999998,
 1.0,
 1.0,
 1.0,
 0.9999999999999998,
 1.0,
 0.8521437889662112,
 0.778800783071405,
 0.697676326071031,
 0.612626394184416,
 0.5272924240430484